### ISSUE TITLE
Allow labels with unicode on Python 2

### ISSUE THREAD

**Issue by EmilStenstrom** [mbr/asciitree#2]
When using unicode labels you currently get a crash on Python 2. Monkey-patching like this fixes the crash:

``` python
import asciitree
asciitree.drawing.Style.label_format = u"{}"
```

... but it would of course be nicer not to have to do that.

Can I ask for a "u" to be added the the formatting string in asciitree.drawing.Style.label_format?

**Comment by mbr** [comment]
Haven't worked with the codebase recently. But if you make a pull request, I'll promise to merge it =).
